apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webhook
  namespace: ditto-deploy
spec:
  secretName: webhook-certificate
  dnsNames:
    - webhook.ditto-deploy.svc
    - webhook.ditto-deploy.svc.cluster.local
  issuerRef:
    name: self-signing-issuer
    kind: Issuer