kind: MutatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1
metadata:
  name: ditto-deploy
  annotations:
    cert-manager.io/inject-ca-from: ditto-deploy/webhook
webhooks:
  - name: ditto-deploy.munagekar.dev
    namespaceSelector:
      matchLabels:
        ditto-deploy: enable
    rules:
      - operations: [ "UPDATE" ]
        apiGroups: [ "apps" ]
        apiVersions: [ "v1" ]
        resources: [ "deployments"]
    clientConfig:
      service:
        namespace: ditto-deploy
        name: webhook
        path: /mutate/deployment
    failurePolicy: 'Fail'
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]