apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: testing
  annotations:
    ditto-deploy: replicas,nginx.limits.cpu,nginx.requests.*
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 7
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.25.1
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "250m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "512Mi"