name: Run CI

on:
  pull_request:
    branches:
    - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry==1.3.1
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.4'
          cache: 'poetry'
      - run: poetry install
      - run: make lint
